apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: dev-api
spec:
  podSelector:
    matchLabels:
      app: dev-api
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - port: 5175
          protocol: TCP
  egress:
    # Allow DNS resolution
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
