#!/usr/bin/env python3
"""mirror_drift_engine.py — generate mirror drift status artifacts.

Source of truth:
  - registry/external-mirrors.yaml

Generated artifact:
  - status/mirror-drift.yaml

Goal:
  - Provide a stable, machine-readable drift snapshot that can be consumed by
    dashboards and CI.
  - Enforce "no manual edits" by checking that the committed status artifact
    matches the registry source.

Dependencies:
  - Stdlib + PyYAML only.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError:  # pragma: no cover
    print("ERROR: PyYAML required (pip install pyyaml)", file=sys.stderr)
    raise

REPO_ROOT = Path(__file__).resolve().parents[1]
REGISTRY_PATH = REPO_ROOT / "registry" / "external-mirrors.yaml"
STATUS_PATH = REPO_ROOT / "status" / "mirror-drift.yaml"

HEADER = """# status/mirror-drift.yaml
# Machine-readable snapshot of mirror drift state.
# Source of truth: registry/external-mirrors.yaml

"""


def _load_yaml(path: Path) -> Any:
    return yaml.safe_load(path.read_text("utf-8"))


def _canonical_generated_at(registry: dict[str, Any]) -> str:
    # Deterministic timestamp: derive from registry.updated_at (date string).
    # This avoids CI drift caused by wall-clock timestamps.
    updated_at = str(registry.get("updated_at") or "").strip()
    if not updated_at:
        return "1970-01-01T00:00:00Z"
    # If it's already an ISO timestamp, keep it; else assume YYYY-MM-DD.
    if "T" in updated_at:
        return updated_at
    return f"{updated_at}T00:00:00Z"


def _strip_nones(d: dict[str, Any]) -> dict[str, Any]:
    return {k: v for k, v in d.items() if v is not None}


def build_payload(registry: dict[str, Any]) -> dict[str, Any]:
    mirrors = registry.get("mirrors") or []
    if not isinstance(mirrors, list):
        raise ValueError("registry/external-mirrors.yaml: mirrors must be a list")

    rows: list[dict[str, Any]] = []
    for m in mirrors:
        if not isinstance(m, dict):
            continue
        upstream = m.get("upstream") or {}
        drift = m.get("drift") or {}
        if not isinstance(upstream, dict):
            upstream = {}
        if not isinstance(drift, dict):
            drift = {}

        row = _strip_nones(
            {
                "name": m.get("name"),
                "org": m.get("org"),
                "url": m.get("url"),
                "upstream_url": upstream.get("url"),
                "upstream_ref": upstream.get("ref"),
                "upstream_head_sha": upstream.get("head_sha"),
                "checked_at": upstream.get("checked_at"),
                "mirror_head_sha": m.get("mirror_head_sha"),
                "drift_status": drift.get("status") or "unknown",
                "drift_note": drift.get("note"),
            }
        )
        # Require minimal identity.
        if not row.get("name"):
            continue
        rows.append(row)

    rows.sort(key=lambda r: str(r.get("name")))

    payload: dict[str, Any] = {
        "version": str(registry.get("version") or "1.0.0"),
        "generated_at": _canonical_generated_at(registry),
        "mirrors": rows,
        "notes": [
            "Generated by engines/mirror_drift_engine.py from registry/external-mirrors.yaml; do not edit manually.",
        ],
    }
    return payload


def render(payload: dict[str, Any]) -> str:
    body = yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    return HEADER + body


def cmd_generate(_: argparse.Namespace) -> int:
    if not REGISTRY_PATH.exists():
        print(f"ERROR: missing {REGISTRY_PATH}", file=sys.stderr)
        return 2
    registry = _load_yaml(REGISTRY_PATH) or {}
    if not isinstance(registry, dict):
        print("ERROR: registry/external-mirrors.yaml must parse to a mapping", file=sys.stderr)
        return 2

    payload = build_payload(registry)
    STATUS_PATH.parent.mkdir(parents=True, exist_ok=True)
    STATUS_PATH.write_text(render(payload), encoding="utf-8")
    print(f"OK: wrote {STATUS_PATH}")
    return 0


def cmd_check(_: argparse.Namespace) -> int:
    if not REGISTRY_PATH.exists():
        print(f"ERROR: missing {REGISTRY_PATH}", file=sys.stderr)
        return 2
    if not STATUS_PATH.exists():
        print(f"ERROR: missing {STATUS_PATH}. Run: python3 engines/mirror_drift_engine.py generate", file=sys.stderr)
        return 2

    registry = _load_yaml(REGISTRY_PATH) or {}
    if not isinstance(registry, dict):
        print("ERROR: registry/external-mirrors.yaml must parse to a mapping", file=sys.stderr)
        return 2

    expected = build_payload(registry)
    current = _load_yaml(STATUS_PATH) or {}
    if not isinstance(current, dict):
        print("ERROR: status/mirror-drift.yaml must parse to a mapping", file=sys.stderr)
        return 2

    if current != expected:
        print("ERROR: status/mirror-drift.yaml is out of date.", file=sys.stderr)
        print("Run: python3 engines/mirror_drift_engine.py generate", file=sys.stderr)
        return 2

    print("OK: mirror drift status matches registry")
    return 0


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    sub = p.add_subparsers(dest="cmd", required=True)

    sp = sub.add_parser("generate", help="Generate status/mirror-drift.yaml")
    sp.set_defaults(fn=cmd_generate)

    sp = sub.add_parser("check", help="Verify status/mirror-drift.yaml matches the registry")
    sp.set_defaults(fn=cmd_check)

    args = p.parse_args()
    return int(args.fn(args))


if __name__ == "__main__":
    raise SystemExit(main())
