#!/usr/bin/env python3
"""Run SocioSphere proof workspace controller gates.

This is a metadata gate runner. It checks that the materialized proof workspace
has the minimum cross-repo control-plane conditions required before deeper proof
execution is attempted. It does not execute mathematical proof tests.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

try:
    import tomllib  # Python 3.11+
except ModuleNotFoundError:  # pragma: no cover
    tomllib = None  # type: ignore[assignment]


ROOT = Path(__file__).resolve().parents[1]
PROOF_MANIFEST = ROOT / "manifest" / "proof-workspace.toml"
ADJACENCY_REGISTRY = ROOT / "registry" / "proof-adjacency-ranking.v0.yaml"
OUTPUT_DIR = ROOT / "status" / "proof-apparatus"
GATE_REPORT_JSON = OUTPUT_DIR / "gate-report.json"
GATE_REPORT_MD = OUTPUT_DIR / "gate-report.md"

TOP_THREE_CLAIMS = {
    "HG-ADJ-001-soule-voisin-atiyah-hirzebruch-torsion",
    "HG-ADJ-002-beilinson-regulator-toy-families",
    "HG-ADJ-003-k3-tate-comparison-template",
}


def fail(message: str) -> None:
    print(f"proof workspace gate runner failed: {message}", file=sys.stderr)
    raise SystemExit(1)


def load_toml(path: Path) -> dict[str, Any]:
    if tomllib is None:
        fail("Python tomllib is unavailable; use Python 3.11+")
    try:
        with path.open("rb") as handle:
            return tomllib.load(handle)
    except Exception as exc:
        fail(f"cannot load TOML {path}: {exc}")


def load_json(path: Path) -> dict[str, Any]:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception as exc:
        fail(f"cannot load JSON {path}: {exc}")


def gate(gates: list[dict[str, Any]], gate_id: str, passed: bool, detail: str) -> None:
    gates.append({"gate_id": gate_id, "status": "pass" if passed else "fail", "detail": detail})


def write_reports(gates: list[dict[str, Any]]) -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    GATE_REPORT_JSON.write_text(json.dumps({"gates": gates}, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    lines = [
        "# Proof Apparatus Gate Report",
        "",
        "Generated by `tools/run_proof_workspace_gates.py`.",
        "",
        "This is controller metadata. Passing these gates does not promote theorem status.",
        "",
        "| Gate | Status | Detail |",
        "|---|---|---|",
    ]
    for item in gates:
        lines.append(f"| {item['gate_id']} | {item['status']} | {str(item['detail']).replace('|', '\\|')} |")
    GATE_REPORT_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    manifest = load_toml(PROOF_MANIFEST)
    repos = manifest.get("repos")
    if not isinstance(repos, list) or not repos:
        fail("proof workspace manifest has no repos")

    gates: list[dict[str, Any]] = []
    adapters: dict[str, dict[str, Any]] = {}

    registry_text = ADJACENCY_REGISTRY.read_text(encoding="utf-8") if ADJACENCY_REGISTRY.exists() else ""
    gate(
        gates,
        "proof-adjacency-registry-integrated",
        all(term in registry_text for term in ["adjacency_axes:", "ranking:", "Atiyah-Hirzebruch", "Beilinson regulator", "K3-type comparison"]),
        "Registry contains axes, ranking, and top-three scoped entries.",
    )

    missing = []
    for repo in repos:
        adapter_path = ROOT / repo["local_path"] / "proof-adapter.json"
        if not adapter_path.exists():
            missing.append(str(adapter_path))
            continue
        adapter = load_json(adapter_path)
        adapters[adapter["repo"]] = adapter

    gate(
        gates,
        "all-proof-adapters-materialized",
        not missing and len(adapters) == len(repos),
        "All declared proof repos expose proof-adapter.json." if not missing else ", ".join(missing),
    )

    gate(
        gates,
        "controller-protocol-consistency",
        all(adapter.get("controller_protocol") == "protocol/proof-apparatus-workspace/v0" for adapter in adapters.values()),
        "Every adapter points at the SocioSphere proof apparatus workspace protocol.",
    )

    hg = adapters.get("SocioProphet/Heller-Godel", {})
    hg_claims = {claim.get("claim_id") for claim in hg.get("claims", [])}
    gate(
        gates,
        "top-three-scoped-in-heller-godel",
        TOP_THREE_CLAIMS.issubset(hg_claims),
        "Heller-Godel declares the three scoped adjacency claims.",
    )

    promoted_claims = []
    boundaryless_claims = []
    for adapter in adapters.values():
        for claim in adapter.get("claims", []):
            if claim.get("state") == "promoted":
                promoted_claims.append(f"{adapter.get('repo')}:{claim.get('claim_id')}")
            if not claim.get("boundary"):
                boundaryless_claims.append(f"{adapter.get('repo')}:{claim.get('claim_id')}")

    gate(
        gates,
        "no-theorem-promotion-from-adjacency",
        not promoted_claims,
        "No adapter claim is in promoted state." if not promoted_claims else ", ".join(promoted_claims),
    )
    gate(
        gates,
        "all-claims-have-boundaries",
        not boundaryless_claims,
        "All adapter claims have explicit boundaries." if not boundaryless_claims else ", ".join(boundaryless_claims),
    )

    bsd = adapters.get("SocioProphet/bsd-proof-program", {})
    ym = adapters.get("SocioProphet/yang-mills", {})
    gate(
        gates,
        "active-programs-not-paper-i-fallout",
        len(bsd.get("claims", [])) == 0 and len(ym.get("claims", [])) == 0,
        "BSD and Yang-Mills remain active methodology-adjacent programs, not Paper I fallout claims.",
    )

    write_reports(gates)
    failed = [item for item in gates if item["status"] != "pass"]
    if failed:
        fail("failed gates: " + ", ".join(item["gate_id"] for item in failed))

    print(f"proof workspace gates passed: {len(gates)} gates")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
